using System;
using System.Collections.Generic;

namespace ChatBot
{
    public class ResponseEngine
    {
        private Dictionary<string, string> responses;

        public ResponseEngine()
        {
            responses = new Dictionary<string, string>
                        (StringComparer.OrdinalIgnoreCase)
            {
               { "how are you", "I'm running smoothly! All my defensive protocols are online. How can I help you improve your cybersecurity today?" },
               { "tell me about cybersecurity", "Cybersecurity is the practice of protecting systems, networks, and programmes from digital attacks. It's all about keeping your personal information, like passwords and bank details, out of the hands of cybercriminals." },
    
    { "what should i type", "You can type any questions you have about online safety! Try typing a topic like 'passwords', 'phishing', or 'public wifi' to see what I know." },
    
    { "keywords", "Some of the keywords I recognise are: password, phishing, safe browsing, 2FA, malware, VPN, firewall, and ransomware. Just type one of those to learn more!" },
    
    { "help", "I'm here to help! You can ask me to explain specific cybersecurity terms, or just type 'list' to see a full breakdown of what we can talk about." }, 
    { "how do you work", "I am a console-based programme written in C#. I take what you type, clean up the text, and look for specific keywords to match with a dictionary of cybersecurity facts that my developer programmed into me!" },
    
    { "how do you exactly work", "I am a console-based programme written in C#. I take what you type, clean up the text, and look for specific keywords to match with a dictionary of cybersecurity facts that my developer programmed into me!" },
    
    { "list", "I can teach you about a variety of topics! Try asking me about passwords, phishing, safe browsing, 2FA, malware, VPNs, firewalls, or public Wi-Fi." },
    
    { "what can you do", "I'm here to answer your questions and test your knowledge! You can ask me to explain concepts like ransomware or identity theft, or just ask for a list of topics we can discuss." },
    

    { "password", "Strong passwords are your first line of defence. Always use a combination of uppercase and lowercase letters, numbers, and symbols. Aim for at least 12 characters. I highly recommend using a reputable password manager so you don't have to memorise them all!" },
    
    { "phishing", "Phishing is when cybercriminals try to trick you into revealing sensitive information, like passwords or bank details, usually via email or text. Always look out for a false sense of urgency, suspicious sender addresses, and poor spelling. Never click on unexpected links!" },
    
    { "safe browsing", "Safe browsing starts with checking for 'https://' and the padlock icon in your browser's address bar, which means the connection is encrypted. Also, avoid downloading files from untrusted sources and consider using a reliable ad-blocker." },
    
    { "2fa", "Two-Factor Authentication (2FA) adds an essential extra layer of security. Even if a hacker guesses your password, they can't access your account without the second factor, which is usually a code sent to your phone or generated by an authenticator app." },
    
    { "malware", "Malware is malicious software designed to harm or exploit your device. This includes viruses, worms, and ransomware. To protect yourself, always keep your operating system updated and use a good, trusted antivirus programme." },
    
    { "vpn", "A Virtual Private Network (VPN) encrypts your internet traffic and hides your IP address. It's especially important to use a VPN when connecting to public Wi-Fi networks, like at a café, to stop anyone from snooping on your data." },
    
    
    { "encryption", "Encryption scrambles your readable data into an unreadable format. Only someone with the correct 'key' or password can unscramble and read it. It's absolutely essential for protecting sensitive messages and files." },
    
    { "password manager", "A password manager is a secure programme that generates and stores incredibly strong, unique passwords for all your accounts in an encrypted vault. You only need to memorise one master password to access them all!" },         
            };
        }

        public string GetResponse(string userInput)
        {
            foreach (var entry in responses)
            {
                if (userInput.IndexOf(entry.Key,
                    StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return entry.Value;
                }
            }
            return null; // signals ChatBot.cs that no match was found
        }

        public bool IsExitCommand(string userInput)
        {
            string lower = userInput.ToLower().Trim();
            return lower == "bye" || lower == "exit" || lower == "quit";
        }
    }
}
